### ISSUE TITLE
Use .cleanContent when indexing messages

### ISSUE THREAD

**Issue by RhysSullivan** [rafaelalmeidatk/nextjs-forum#28]
It converts users, channels, and server mentions from their ids to their real name to make it more readable 

Long term it'd be better to convert from the ids but it's a lot easier to use clean content in the short term.

https://old.discordjs.dev/#/docs/discord.js/main/class/Message?scrollTo=cleanContent

**Comment by rafaelalmeidatk** [comment]
This looks very useful! But since we have the hidden profiles I think I prefer to have the broken usernames than showing their discord usernames, it would be great if there was a way to transform only the channel names.

I will focus next on converting the IDs so the mentions aren't so weird for too much time
